### ISSUE TITLE
Text bei Misserfolg anpassen

### ISSUE THREAD

**Issue by RundesBalli** [Pacerino/pr0gramm_music#3]
https://github.com/Pacerino/pr0gramm_music/blob/f37a57301591c12d79f718ad94da861106c8c54f/src/services/Pr0Service.ts#L80

Wenn man mit einem Useraccount 5x hintereinander in Zeitspanne X (mir unbekannt) ein und die selbe Nachricht kommentiert, dann wird man gebannt wegen Kommentarspam/-vandalismus. Ob das bei einem Userbot auch so ist weiß ich nicht. Ich würde aber einfach eine Rotation in diesen Text einbauen oder irgendwie eine Art von Unique Wert (z.B. Uhrzeit, Timestamp, etc.) um nicht in diese Regelung zu fallen.

**Comment by Pacerino** [comment]
In der Theorie hast du vollkommen recht, in der Praxis habe ich es allerdings nicht mitbekommen, dass der Bot gebannt wurde.
Ich werde mir die Sache dennoch mal anschauen und eine Rotation einbauen. In wie fern diese aussehen wird, weiß ich noch nicht.

**Comment by RundesBalli** [comment]
Da Bots auch in API Limits hängen und vom Ratelimit nicht ausgeschlossen sind, könnte ich mir vorstellen, dass auch dieses Limit hier greift.

Ich würde einfach folgendes drunter schreiben:

`Zeitpunkt der Überprüfung: 2021-07-14, 18:02:10`

**Comment by RundesBalli** [comment]
Danke!
