### ISSUE TITLE
Lied taggen

### ISSUE THREAD

**Issue by RundesBalli** [Pacerino/pr0gramm_music#6]
Ich fände es praktisch, wenn der Bot automatisch den Titel, den Interpreten und wenns möglich ist (32 Zeichen Taglänge) auch das Lied mit dem Interpreten zusammen Taggen würde.

Also als Beispiel Tags:
`Titel`
`Interpret`
`Interpret - Titel` (wenn Länge ≤ 32)

**Comment by Pacerino** [comment]
Ich kläre das mal mit dem Team. Möchte erstmal sicher sein ob das vom Team aus klar geht.

**Comment by RundesBalli** [comment]
Das Lied wird oft von Usern nachgetaggt. Wüsste nicht wieso das ein Problem sein sollte. Aber klar, besser vorher einmal fragen, bevor man umsonst gearbeitet hat.

**Comment by Pacerino** [comment]
Hmmm... Hast auch recht. Ich habe mal 5yn74x gefragt. Ich melde mich sobald er geantwortet hat!

**Comment by Pacerino** [comment]
Theoretisch ist es schon möglich. Da es aber noch einen Fehler in der node-pr0gramm-api gibt, muss ich darauf warten.

https://github.com/holzmaster/node-pr0gramm-api/pull/28

**Comment by RundesBalli** [comment]
Danke!

**Comment by Pacerino** [comment]
Wird jetzt gesetzt!

**Comment by RundesBalli** [comment]
Ausgezeichnet!
